[tool.poetry]
name = "data-product-manager"
version = "3.3.0"
description = "Data Product Manager component of the Data Fabric"
authors = ["Lucía Cabanillas Rodríguez, David Martínez García"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.104.1"
pydantic = "^2.4.2"
uvicorn = "^0.23.2"
jinja2 = "^3.1.2"
python-multipart = "^0.0.6"
requests = "^2.31.0"
urllib3 = "1.26.7"
croniter = "^2.0.1"
kubernetes = "^28.1.0"
pymongo = "^4.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
