---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-configmaps-helmrelease-helmrepository
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]

- apiGroups: ["source.toolkit.fluxcd.io"]
  resources: ["helmrepositories"]
  verbs: ["create"]

- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-configmaps-helmrelease-helmrepository
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: ClusterRole
  name: create-configmaps-helmrelease-helmrepository
  apiGroup: rbac.authorization.k8s.io
