# values.yaml
replicaCount: 1
name: DataProductManager
image:
  repository: registry.gitlab.aeros-project.eu/aeros-public/common-deployments/data-fabric/data-product-manager
  tag: latest
  pullPolicy: IfNotPresent
